version: "3"

services:

  web1:
    image: nginx
    container_name: web1
    ports:
        - "81:80"
  web2:
     image: nginx
     container_name: web2
     ports:
        - "82:80"
  haproxy:
     build: ./haproxy
     image: haproxy
     container_name: haproxy
     ports:
       - "80:80"
